- name: Install required packages
  become: yes
  apt:
      update_cache: yes
      name:
          - tcplay
          - python3-setuptools
          - python3-pip
          - expect
          - util-linux
          - cryptsetup
      state: present
