- name: Mount a volume usually with the secret passphrase
  become: yes
  no_log: "{{ hide_sensitive_output }}"
  shell: "/usr/local/bin/tcmount-{{ enc_mount_name }}.sh '{{ enc_hidden_volume_passphrase }}'"
